---
root: true
#  https://eslint.org/docs/rules/
env:
  node: true
  es2020: true
parserOptions:
  ecmaVersion: 2020
plugins:
  - jest
  - custom-lint-rules
extends:
  - "eslint:recommended"
  - "plugin:jest/recommended"
  - prettier
rules:
  no-unused-vars: [error, { argsIgnorePattern: "req|res|next" }]
  no-restricted-modules: [error, child_process, fs] # security
  no-eval: [error] # security
  no-implied-eval: [error] # security
  no-console: [error] # ops
  strict: [error]
  curly: [error]
  no-constant-condition: [error, { checkLoops: false }]
  custom-lint-rules/cds-where-check: [error]
  custom-lint-rules/cds-handler-registration: [error]
