---
root: true
#  https://eslint.org/docs/rules/
env:
  node: true
  es2022: true
parserOptions:
  ecmaVersion: 2022
plugins:
  - jest
extends:
  - "eslint:recommended"
  - "plugin:jest/recommended"
  - prettier
rules:
  no-unused-vars: [error, { argsIgnorePattern: "req|res|next" }]
  no-eval: [error] # security
  no-implied-eval: [error] # security
  no-console: [error] # ops
  strict: [error]
  curly: [error]
  no-constant-condition: [error, { checkLoops: false }]
  # NOTE: the jest intended way of adding __mocks__ in the production code structure is not an option for me and this
  #  is the best alternative I could find.
  jest/no-mocks-import: [off]
