### read state
GET {{base_url}}/rest/feature/state
Authorization: Basic system system

### redis_update | fts 1
POST {{base_url}}/rest/feature/redisUpdate
Authorization: Basic system system
Content-Type: application/json

{
  "key": "/fts/check-service-extension",
  "value": true
}

### redis_update | fts 2
POST {{base_url}}/rest/feature/redisUpdate
Authorization: Basic system system
Content-Type: application/json

{
  "key": "/fts/check-service-extension",
  "value": false,
  "scope": { "user": "alice@wonderland.com" }
}

### redis_update | memory 1
POST {{base_url}}/rest/feature/redisUpdate
Authorization: Basic system system
Content-Type: application/json

{
  "key": "/memory/logInterval",
  "value": 1000
}

### redis_update | memory 2
POST {{base_url}}/rest/feature/redisUpdate
Authorization: Basic system system
Content-Type: application/json

{
  "key": "/memory/logInterval",
  "value": 100
}

### redis_update | memory off
POST {{base_url}}/rest/feature/redisUpdate
Authorization: Basic system system
Content-Type: application/json

{
  "key": "/memory/logInterval",
  "value": null
}

### redis_update | check 1
POST {{base_url}}/rest/feature/redisUpdate
Authorization: Basic system system
Content-Type: application/json

{
  "key": "/check/priority",
  "value": 1
}

### redis_update | check 2
POST {{base_url}}/rest/feature/redisUpdate
Authorization: Basic system system
Content-Type: application/json

{
  "key": "/check/priority",
  "value": 10,
  "scope": { "tenant": "people" }
}

### redis_update | check 3
POST {{base_url}}/rest/feature/redisUpdate
Authorization: Basic system system
Content-Type: application/json

{
  "key": "/check/priority",
  "value": 100,
  "scope": { "user": "alice@wonderland.com" }
}


### redis_update | reset
POST {{base_url}}/rest/feature/redisUpdate
Authorization: Basic system system
Content-Type: application/json

[
  {
    "key": "/check/priority",
    "value": null,
    "options": {
      "clearSubScopes": true
    }
  },
  {
    "key": "/memory/logInterval",
    "value": null,
    "options": {
      "clearSubScopes": true
    }
  },
  {
    "key": "/fts/check-service-extension",
    "value": null,
    "options": {
      "clearSubScopes": true
    }
  }
]

### redis | send command
POST {{base_url}}/rest/feature/redisSendCommand
Authorization: Basic system system
Content-Type: application/json

{
  "command": ["INFO"]
}
